### ISSUE TITLE
Dar permissão de admin para seu sócio da BF

### ISSUE THREAD

**Issue by caloni** [tiodb/tiodb#6]
Pull request de c.? é r.*.

**Comment by rodrigostrauss** [comment]
Mmmm... eu prefiro fazer tudo por pull request. Até as minhas coisas mesmo estão vindo via pull request. Pra parece um projeto open source de verdade... Pode ser? :-)

**Comment by caloni** [comment]
Não vejo por que não. Não tem prazo, mesmo 😁 

-----Original Message-----
